baseURL = "https://paulmurray.pm/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Paul Murray"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Paul Murray"
  description = "Practitioner of some trades, master of none."
  bio = "Practitioner of some trades, master of none. Linux user, not Arch btw. Email: pm (at) paulmurray (dot) pm."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
